### ISSUE TITLE
ros2 galactic / ubuntu 20.04 installation fail

### ISSUE THREAD

**Issue by altineller** [micro-ROS/micro_ros_tivac_launchpad_app#4]
make command fails, building the default micro_ros_tivac_launchpad_app on ubuntu 20.04.. however I have better log this time:

```
Starting >>> lifecycle_msgs                                                                                             
Starting >>> std_srvs
--- stderr: lifecycle_msgs                                                                                                                                                                      
CMake Error at /home/ubuntu/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_typesupport_c/cmake/get_used_typesupports.cmake:35 (message):
  No 'rosidl_typesupport_cpp' found
Call Stack (most recent call first):
  /opt/ros/galactic/share/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp-extras.cmake:8 (get_used_typesupports)
  /opt/ros/galactic/share/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cppConfig.cmake:41 (include)
  /home/ubuntu/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_default_generators/cmake/rosidl_default_generators-extras.cmake:21 (find_package)
  /home/ubuntu/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_default_generators/cmake/rosidl_default_generatorsConfig.cmake:41 (include)
  CMakeLists.txt:14 (find_package)


---
Failed   <<< lifecycle_msgs [0.93s, exited with code 1]
Aborted  <<< builtin_interfaces [0.99s]
Aborted  <<< micro_ros_msgs [0.95s]
Aborted  <<< std_srvs [0.91s]
Aborted  <<< unique_identifier_msgs [0.97s]

Summary: 24 packages finished [12.5s]
  1 package failed: lifecycle_msgs
  4 packages aborted: builtin_interfaces micro_ros_msgs std_srvs unique_identifier_msgs
  8 packages had stderr output: builtin_interfaces lifecycle_msgs micro_ros_msgs microxrcedds_client rcutils rmw std_srvs unique_identifier_msgs
  33 packages not processed
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -Itivaware_c_series/examples/boards/ek-tm4c123gxl/ -Itivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/microros.o src/microros.c
In file included from src/microros.c:2:
src/./microros_usbcdc_transport.h:8:10: fatal error: rmw_microros/custom_transport.h: No such file or directory
    8 | #include <rmw_microros/custom_transport.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [tivaware_c_series/makedefs:175: gcc/microros.o] Error 1
```

Best regards,
Can

**Comment by altineller** [comment]
[colcon-common-extensions.txt](https://github.com/micro-ROS/micro_ros_tivac_launchpad_app/files/8444398/colcon-common-extensions.txt)
[make.txt](https://github.com/micro-ROS/micro_ros_tivac_launchpad_app/files/8444399/make.txt)
[make2.txt](https://github.com/micro-ROS/micro_ros_tivac_launchpad_app/files/8444400/make2.txt)

on a default lxc image with ros-galactic installed, when pip3 install colcon-common-extensions is run, it gives a warning like:

ERROR: pytest-rerunfailures 10.2 has requirement pytest>=5.3, but you'll have pytest 4.6.9 which is incompatible.

After this, I upgraded pytest to 7.1.1 with pip3, but the install still fails - for an irrelevant reason - and that is logged in make2.txt

Best Regards,
Can Altineller

**Comment by Acuadros95** [comment]
I can't replicate this on netiehr on my local ubuntu 20.04 or `ubuntu:latest` and `ros:galactic` docker images.

Could you give more info about your environment? How did you install ROS?

We may need to add the upgrade flag `-U` on this command to fix that versioning errors:
> pip3 install -U catkin_pkg lark-parser empy colcon-common-extensions

**Comment by altineller** [comment]
Ok, it is fixed. It was a combination of number of things.

First, 

pip3 install -U pytest

and then 

pip3 install -U catkin_pkg lark-parser empy colcon-common-extensions

is required. Also the .local/bin must be in path, and /opt/ros/galactic/setup.bash must not be sourced.

if /opt/ros/galactic/setup.bash is sourced, then compilation fails.

Best Regards,
Can
