### ISSUE TITLE
Ubuntu 22, ROS2 Humble, humble branch, build error 

### ISSUE THREAD

**Issue by aliozcan01** [micro-ROS/micro_ros_tivac_launchpad_app#9]
Hello, 

I'm getting errors while build. Could you help me ?

--- stderr: unique_identifier_msgs                                                         
CMake Error at /home/ali/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_typesupport_c/cmake/get_used_typesupports.cmake:35 (message):
  No 'rosidl_typesupport_cpp' found

src/./microros_usbcdc_transport.h:8:10: fatal error: rmw_microros/custom_transport.h: No such file or directory
    8 | #include <rmw_microros/custom_transport.h>

Best regards.

**Comment by pablogs9** [comment]
Can you provide information about how are you building this package?

**Comment by aliozcan01** [comment]
I followed the steps in the readme.

**Comment by pablogs9** [comment]
We need more information about your environment. Your build logs, your procedure... If this include is not available probably your micro-ROS client library is not being generated correctly, but we need more info

**Comment by aliozcan01** [comment]
**I did a reinstall on another computer just to be sure.**

**I installed Ubuntu 22. (dual boot)**

**Then i installed ROS2 Humble:**

https://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html ;
sudo apt install software-properties-common
sudo add-apt-repository universe
sudo apt update && sudo apt install curl
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
sudo apt update
sudo apt upgrade
sudo apt install ros-humble-desktop
sudo apt install ros-humble-ros-base
sudo apt install ros-dev-tools
source /opt/ros/humble/setup.bash

**Finally, I try to  install this repo.**

https://github.com/micro-ROS/micro_ros_tivac_launchpad_app ;
sudo apt install python3-pip
pip3 install catkin_pkg lark-parser empy colcon-common-extensions
git clone --recursive https://github.com/micro-ROS/micro_ros_tivac_launchpad_app.git
cd micro_ros_tivac_launchpad_app
Download EK-TM4C123GXL Kit Software
Extract EK-TM4C123GXL Kit Software to tivaware_c_series folder

In make file: ROOT=tivaware_c_series ---> ROOT=/home/ali/tivaware_c_series

make

1.Error: (resolved)
--- stderr: microcdr                                         
CMake Error at cmake/SuperBuild.cmake:19 (enable_language):
  The CMAKE_C_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.
Solution: sudo apt-get install gcc-arm-none-eabi

Then, make clean and make

Errors:

--- stderr: builtin_interfaces                                           
CMake Error at /home/ali/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_typesupport_c/cmake/get_used_typesupports.cmake:35 (message):
  No 'rosidl_typesupport_cpp' found
Call Stack (most recent call first):
  /opt/ros/humble/share/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cpp-extras.cmake:8 (get_used_typesupports)
  /opt/ros/humble/share/rosidl_typesupport_cpp/cmake/rosidl_typesupport_cppConfig.cmake:41 (include)
  /home/ali/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_default_generators/cmake/rosidl_default_generators-extras.cmake:21 (find_package)
  /home/ali/micro_ros_tivac_launchpad_app/microros/install/micro_ros_src/install/share/rosidl_default_generators/cmake/rosidl_default_generatorsConfig.cmake:41 (include)
  CMakeLists.txt:14 (find_package)

In file included from src/microros.c:2:
src/./microros_usbcdc_transport.h:8:10: fatal error: rmw_microros/custom_transport.h: No such file or directory
    8 | #include <rmw_microros/custom_transport.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by pablogs9** [comment]
Try to build micro-ROS without sourcing ` /opt/ros/humble/setup.bash`, make sure that your `bashrc` is not sourcing it.

**Comment by aliozcan01** [comment]
**When I removed the source, the previous error was resolved, thank you very much.
Now there is a different errors (failed: No such file or directory).**

Finished <<< rclc [3.58s]
Starting >>> rclc_lifecycle
Starting >>> rclc_parameter
Finished <<< nav_msgs [7.62s]                                                                                                                              
Finished <<< rclc_lifecycle [1.29s]                                                                                                   
Finished <<< rclc_parameter [1.44s]                                                                  
Finished <<< sensor_msgs [13.9s]                         
Starting >>> stereo_msgs
Starting >>> visualization_msgs
Starting >>> sensor_msgs_py                                                          
stderr: sensor_msgs_py                                                                                               
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(

Finished <<< sensor_msgs_py [0.87s]
Finished <<< stereo_msgs [2.37s]                                                                         
Finished <<< visualization_msgs [6.17s]                        
Starting >>> common_interfaces
Finished <<< common_interfaces [0.57s]                     

Summary: 64 packages finished [51.2s]
  16 packages had stderr output: microxrcedds_client rcl rcl_lifecycle rclc rcutils rmw rmw_microxrcedds ros2trace rosidl_cli sensor_msgs_py test_tracetools_launch tf2_msgs tracetools_launch tracetools_read tracetools_test tracetools_trace
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rsync is already the newest version (3.2.3-8ubuntu3.1).
rsync set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/common_interfaces/common_interfaces" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/microcdr/microcdr" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/microxrcedds_client/microxrcedds_client" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rcl_logging_noop/rcl_logging_noop" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rclc/rclc" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rclc_lifecycle/rclc_lifecycle" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rclc_parameter/rclc_parameter" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rmw_implementation/rmw_implementation" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rmw_implementation_cmake/rmw_implementation_cmake" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rmw_microxrcedds/rmw_microxrcedds" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/ros2trace/ros2trace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_adapter/rosidl_adapter" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_cli/rosidl_cli" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_cmake/rosidl_cmake" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_default_generators/rosidl_default_generators" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_default_runtime/rosidl_default_runtime" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_generator_c/rosidl_generator_c" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_generator_cpp/rosidl_generator_cpp" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_parser/rosidl_parser" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_runtime_cpp/rosidl_runtime_cpp" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_cpp/rosidl_typesupport_cpp" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_introspection_tests/rosidl_typesupport_introspection_tests" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_microxrcedds_c/rosidl_typesupport_microxrcedds_c" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_microxrcedds_c_tests/rosidl_typesupport_microxrcedds_c_tests" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_microxrcedds_cpp/rosidl_typesupport_microxrcedds_cpp" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_microxrcedds_cpp_tests/rosidl_typesupport_microxrcedds_cpp_tests" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/rosidl_typesupport_microxrcedds_test_msg/rosidl_typesupport_microxrcedds_test_msg" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/sensor_msgs_py/sensor_msgs_py" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/test_interface_files/test_interface_files" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/test_rmw_implementation/test_rmw_implementation" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/test_tracetools/test_tracetools" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/test_tracetools_launch/test_tracetools_launch" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/tracetools_launch/tracetools_launch" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/tracetools_read/tracetools_read" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/tracetools_test/tracetools_test" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
rsync: [sender] change_dir "/home/ali/micro_ros_tivac_launchpad_app/microros/install/include/tracetools_trace/tracetools_trace" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1333) [sender=3.2.3]
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/microros.o src/microros.c
In file included from microros/install/include/rclc/action_client.h:26,
                 from microros/install/include/rclc/rclc.h:35,
                 from src/microros.c:7:
microros/install/include/rclc/action_goal_handle.h:35:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
   35 |   };
      |    ^
microros/install/include/rclc/action_goal_handle.h:53:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
   53 |   };
      |    ^
microros/install/include/rclc/action_goal_handle.h:58:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
   58 |   };
      |    ^
microros/install/include/rclc/action_goal_handle.h:63:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
   63 |   };
      |    ^
In file included from microros/install/include/rclc/executor.h:30,
                 from src/microros.c:8:
microros/install/include/rclc/executor_handle.h:120:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
  120 |   };
      |    ^
microros/install/include/rclc/executor_handle.h:154:4: warning: ISO C99 doesn't support unnamed structs/unions [-Wpedantic]
  154 |   };
      |    ^
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/syscalls.o src/syscalls.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/microros_usbcdc_transport.o src/microros_usbcdc_transport.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/microros_time.o src/microros_time.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/microros_allocators.o src/microros_allocators.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/startup_gcc.o src/startup_gcc.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/uartstdio.o /home/ali/tivaware_c_series/utils/uartstdio.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/main.o src/main.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/usb_serial_structs.o src/usb_serial_structs.c
arm-none-eabi-gcc -mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -MD -std=c99 -Wall -pedantic -DPART_TM4C123GH6PM -c -g -D DEBUG -O0 -DTARGET_IS_TM4C123_RB1 -DUART_BUFFERED -I/home/ali/tivaware_c_series/examples/boards/ek-tm4c123gxl/ -I/home/ali/tivaware_c_series -Imicroros/install/include -Isrc -Dgcc -o gcc/ustdlib.o /home/ali/tivaware_c_series/utils/ustdlib.c
arm-none-eabi-gcc -o gcc/microros_tivac.elf -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard -Wl,--gc-sections -Wl,--print-memory-usage -T "microros_tivac.ld" --specs=nano.specs gcc/microros.o gcc/syscalls.o gcc/microros_usbcdc_transport.o gcc/microros_time.o gcc/microros_allocators.o gcc/startup_gcc.o gcc/uartstdio.o gcc/main.o gcc/usb_serial_structs.o gcc/ustdlib.o /home/ali/tivaware_c_series/usblib/gcc/libusb.a /home/ali/tivaware_c_series/driverlib/gcc/libdriver.a microros/install/libmicroros.a
Memory region         Used Size  Region Size  %age Used
           FLASH:       77012 B       256 KB     29.38%
            SRAM:       11000 B        32 KB     33.57%
arm-none-eabi-objcopy -O binary gcc/microros_tivac.elf gcc/microros_tivac.bin

**Comment by pablogs9** [comment]
It seems that you have a binary ready to be flashed:

`arm-none-eabi-objcopy -O binary gcc/microros_tivac.elf gcc/microros_tivac.bin`

**Comment by aliozcan01** [comment]
Yes, binary is created. rsync is installed.

**in "generate_microros_library.sh"**

######## Fix include paths  ########
pushd $INSTALL_DIR/micro_ros_src > /dev/null
    INCLUDE_ROS2_PACKAGES=$(colcon list | awk '{print $1}' | awk -v d=" " '{s=(NR==1?s:s d)$0}END{print s}')
popd > /dev/null

apt -y install rsync
for var in ${INCLUDE_ROS2_PACKAGES}; do
    rsync -r $INSTALL_DIR/include/${var}/${var}/* $INSTALL_DIR/include/${var}/
    rm -rf $INSTALL_DIR/include/${var}/${var}/
done

**here is the command for rsync install. I think there is a problem with the file operations here, but I haven't figured out the exact reason yet.**

**Comment by pablogs9** [comment]
Does it works if you flash the binary?

**Comment by aliozcan01** [comment]
I'm pretty new to microros :) I tried to run it after flashing.

I followed the steps here: https://micro.ros.org/docs/tutorials/core/first_application_linux/

Then,
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/ttyACM0
[1674557687.137994] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1674557687.138172] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 4

but I couldn't see an active node or topic. I guess I'm doing something wrong. I'm researching how to do it. If you have a document on this subject, I would be very happy if you share it. By the way, I took a lot of your time, thank you for your help.

**Comment by pablogs9** [comment]
Use `-v6` and reset the board after opening the agent. Also, make sure that the serial port is the correct one, preferably use files under `/dev/serial/by-id/...`

**Comment by aliozcan01** [comment]
ros2 run micro_ros_agent micro_ros_agent serial --dev "/dev/serial/by-id/usb-Texas_Instruments_In-Circuit_Debug_Interface_0E236050-if00" --verbose 6
[1674558915.833730] info     | TermiosAgentLinux.cpp | init                     | running...             | fd: 3
[1674558915.833959] info     | Root.cpp           | set_verbose_level        | logger setup           | verbose_level: 6

Then I pressed the reset button. But I can't see any active nodes or topics.

**Comment by pablogs9** [comment]
It seems that it is not communication with the agent. Do you have any way of debugging your hardware in order to check which code is running?

**Comment by aliozcan01** [comment]
I don't know, I'll investigate. Thank you.
